package:
  name: uibcdf_test_systems
  version: 0.0.1

source:
  path: ../../

build:
  number: 1

requirements:
  build:
    - python  {{ python }}
    - setuptools
    - numpy 

  run:
    - python  {{ python }}
    - numpy
    - openmm
    - sympy

about:
  home: https://uibcdf.org
  license: MIT License
  summary: ""
  description: |
    This toolkit library provides some useful classes, functions, pipes and wrappers daily used in the uibcdf lab when molecular systems and molecular dynamics are manipulated.
  dev_url: https://github.com/uibcdf/UIBCDF_test_systems
  doc_url: https://uibcdf.org/UIBCDF_test_systems

